@startuml
class Usuario {
    - id: Long
    - nome: String
    - sobrenome: String
    - cpf: String
    - email: String
    - senha: String
}

abstract class FotoRosto {
    - id: Long
    - nomeArquivo: File
}

class FotoRostoS3 {
    - chaveObjeto: String
    - tamanho: Long
    - bucket: String
}

class FotoRostoDiscoLocal {
    - caminhoArquivo: String
}

class Evento {
    - id: Long
    - descricao: String
    - permiteSolicitacoesIngresso: boolean
    - codigo: String
}

class Localizacao {
    - id: Long
    - descricao: String
    - latitude: String
    - longitude: String
}

class SolicitacaoEvento {
    - id: Long
    - codigo: String
}

enum StatusSolicitacaoEvento << enumeration >> {
    + PENDENTE: int
    + ACEITO: int
    + REJEITADO: int
}

enum TipoSolicitacaoEvento << enumeration >> {
    + SOLICITACAO_INGRESSO: int
    + CONVITE: int
}

class RegistroPonto {
    - id: Long
    - data: LocalDate
    - raioPermitidoEmMetros: Double
}

class Ponto {
    - id: Long
    - dataInicial: LocalDateTime
    - dataFinal: LocalDateTime
}

enum Fator << enumeration >> {
    + RECONHECIMENTO_FACIAL: int
    + LOCALIZACAO: int
}

class PresencaUsuario {
    - id: Long
}

class TentativaValidacaoReconhecimentoFacial {
    - id: Long
    - dataHora: LocalDateTime
    - validado: boolean
}

class TentativaValidacaoLocalizacao {
    - id: Long
    - distanciaEmMetros: Double
    - raioPermitidoEmMetros: Double
    - latitude: String
    - longitude: String
    - dataHora: LocalDateTime
    - validado: boolean
}

class RegistroPresenca {
    - id: Long
    - frValidadoComSucesso: boolean
    - localizacaoValidadaComSucesso: boolean
    - validadoPeloAdministrador: boolean
}

enum StatusRegistroPresenca << enumeration >> {
    + PENDENTE: int
    + ACEITO: int
    + REJEITADO: int
}

FotoRostoS3 -up-|> FotoRosto
FotoRostoDiscoLocal -up-|> FotoRosto

Usuario "1" o-> "1" FotoRosto

Evento "1" o-up-> "*" RegistroPonto
Evento "1" o-up-> "*" Localizacao
Evento "*" -down-> "*" Usuario : usuarios
Evento "*" --> "1" Usuario : administrador
Evento "1" *-> "1" SolicitacaoEvento

RegistroPonto "1" *-> "*" Ponto
RegistroPonto "*" o-> "*" Fator
RegistroPonto "*" --> "1" Localizacao
RegistroPonto "1" *-> "*" PresencaUsuario

PresencaUsuario "1" *-> "*" RegistroPresenca
PresencaUsuario "*" o-> "1" Usuario

RegistroPresenca "1" *-down-> "*" TentativaValidacaoReconhecimentoFacial
RegistroPresenca "1" *-up-> "*" TentativaValidacaoLocalizacao
RegistroPresenca "*" *-up-> "1" StatusRegistroPresenca

SolicitacaoEvento "*" --> "1" Usuario : usuario inicial
SolicitacaoEvento "*" --> "1" Usuario : usuario alvo
SolicitacaoEvento "*" *-up-> "1" StatusSolicitacaoEvento
SolicitacaoEvento "*" *-down-> "1" TipoSolicitacaoEvento

@enduml
