@startuml
abstract class DefaultEntity {
    - id: Long
    - updatedAt: LocalDateTime
    - createdAt: LocalDateTime
    - active: boolean
}

class User {
    - id: Long
    - name: String
    - surname: String
    - cpf: String
    - email: String
    - password: String
}

abstract class FacePhoto {
    - id: Long
    - fileName: File
}

class FacePhotoS3 {
    - objectkey: String
    - size: Long
    - bucket: String
}

class FacePhotoLocalDisk {
    - filePath: String
}

class Event {
    - id: Long
    - description: String
    - allowTicketRequests: boolean
    - code: String
}

class Location {
    - id: Long
    - description: String
    - latitude: String
    - longitude: String
}

class EventRequest {
    - id: Long
    - code: String
}

enum EventRequestStatus << enumeration >> {
    + PENDING
    + ACCEPTED
    + REJECTED
}

enum EventRequestType << enumeration >> {
    + TICKET_REQUEST
    + INVITATION
}

class PointRecord {
    - id: Long
    - date: LocalDate
    - allowableRadiusInMeters: Double
}

class Point {
    - id: Long
    - initialDate: LocalDateTime
    - finalDate: LocalDateTime
}

enum Factor << enumeration >> {
    + FACE_RECOGNITION
    + LOCATION
}

class UserAttendance {
    - id: Long
}

class FaceRecognitionValidationAttempt {
    - id: Long
    - dateTime: LocalDateTime
    - validated: boolean
}

class LocationValidationAttempt {
    - id: Long
    - distanceInMeters: Double
    - allowableRadiusInMeters: Double
    - latitude: String
    - longitude: String
    - dateTime: LocalDateTime
    - validated: boolean
}

class AttendanceRecord {
    - id: Long
    - frValidatedSuccessfully: boolean
    - locationValidatedSuccessfully: boolean
    - validatedByAdministrator: boolean
}

enum AttendanceRecordStatus << enumeration >> {
    + PENDING
    + ACCEPTED
    + REJECTED
}

User --|> DefaultEntity
Event --|> DefaultEntity
EventRequest --|> DefaultEntity
PointRecord --|> DefaultEntity
FacePhotoS3 -up-|> FacePhoto
FacePhotoLocalDisk -up-|> FacePhoto
FacePhoto -up-|> DefaultEntity

User "1" o-> "1" FacePhoto

Event "1" o-up-> "*" PointRecord
Event "1" o-up-> "*" Location
Event "*" -down-> "*" User : users
Event "*" --> "1" User : administrator
Event "1" *-> "1" EventRequest

PointRecord "1" *-> "*" Point
PointRecord "*" o-> "*" Factor
PointRecord "*" --> "1" Location
PointRecord "1" *-> "*" UserAttendance

UserAttendance "1" *-> "*" AttendanceRecord
UserAttendance "*" o-> "1" User

AttendanceRecord "1" *-down-> "*" FaceRecognitionValidationAttempt
AttendanceRecord "1" *-up-> "*" LocationValidationAttempt
AttendanceRecord "*" *-up-> "1" AttendanceRecordStatus

EventRequest "*" --> "1" User : initial user
EventRequest "*" --> "1" User : target user
EventRequest "*" *-up-> "1" EventRequestStatus
EventRequest "*" *-down-> "1" EventRequestType

@enduml
