services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root