name: facelocus
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  flutter_svg: ^2.0.9
  dio: ^5.4.0
  provider: ^6.1.1
  geolocator: 10.1.0
  skeletonizer: ^1.1.1
  share_plus: ^7.2.1
  flutter_secure_storage: ^9.0.0
  top_snackbar_flutter: ^3.1.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  face_camera: ^0.1.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  toastification: ^1.2.0
  lottie: ^3.0.0
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  location: ^5.0.3
  loading_indicator: ^3.1.1
  flutter_neat_and_clean_calendar: ^0.3.18+40
  multi_select_flutter: ^4.1.3
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  mask_text_input_formatter: ^2.9.0
  get_it: ^7.7.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Bold.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
